// <auto-generated>
// Placeholder: the traced sprite-sheet poses are generated into this file by the offline tracer.
// Empty tables leave the current animations unchanged.
// </auto-generated>
using System.Collections.Generic;
using Margin.Rendering;

namespace Margin.EditorTools
{
    public static partial class StarterAnimations
    {
        private static readonly string[] TracedAttackMoves = { };

        private static Dictionary<string, FigurePose> TracedPoses() => new Dictionary<string, FigurePose>();

        private static Dictionary<string, ClipSpec> TracedClips() => new Dictionary<string, ClipSpec>();
    }
}
